openapi: 3.1.0
info:
  title: Astro API
  version: 1.0.0
  description: 惑星の位置・ハウス・逆行情報を取得する占星術API
servers:
  - url: https://astroapi-eixi.onrender.com
paths:
  /planet:
    post:
      operationId: getPlanetPositions
      summary: 惑星の位置・ハウス・逆行情報を取得（出生図）
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                year: {type: integer, example: 1979}
                month: {type: integer, example: 5}
                day: {type: integer, example: 5}
                hour: {type: integer, example: 13}
                minute: {type: integer, example: 10}
                location: {type: string, example: Tokyo, Japan}
                latitude: {type: number, example: 35.6895}
                longitude: {type: number, example: 139.6917}
              required: [year, month, day, hour, minute]
      responses:
        "200":
          description: 成功
  /transit:
    post:
      operationId: getTransitPositions
      summary: 現在時刻のトランジット天体位置を取得
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                location: {type: string, example: Tokyo, Japan}
                latitude: {type: number, example: 35.6895}
                longitude: {type: number, example: 139.6917}
      responses:
        "200":
          description: 成功
  /solararc:
    post:
      operationId: getSolarArcPositions
      summary: ソーラーアーク進行天体位置を取得
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                birth_year: {type: integer, example: 1979}
                birth_month: {type: integer, example: 5}
                birth_day: {type: integer, example: 5}
                birth_hour: {type: integer, example: 13}
                birth_minute: {type: integer, example: 10}
                location: {type: string, example: Tokyo, Japan}
                latitude: {type: number, example: 35.6895}
                longitude: {type: number, example: 139.6917}
              required: [birth_year, birth_month, birth_day, birth_hour, birth_minute]
      responses:
        "200":
          description: 成功
