openapi: 3.1.0
info:
  title: Astro API
  version: 1.0.0
  description: 惑星の位置、ハウス、逆行情報などを取得する占星術API
servers:
  - url: https://astroapi-eixi.onrender.com

paths:
  /planet:
    post:
      operationId: getPlanetPositions
      summary: 出生図の惑星位置、ハウス、逆行情報を取得
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                year:
                  type: integer
                  example: 1979
                month:
                  type: integer
                  example: 5
                day:
                  type: integer
                  example: 5
                hour:
                  type: integer
                  example: 12
                minute:
                  type: integer
                  example: 30
                location:
                  type: string
                  example: Tokyo, Japan
                latitude:
                  type: number
                  example: 35.6895
                longitude:
                  type: number
                  example: 139.6917
              required:
                - year
                - month
                - day
                - hour
                - minute
      responses:
        "200":
          description: 惑星データ取得成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  input_datetime_utc:
                    type: string
                    example: 1979-05-05 03:51
                  latitude:
                    type: number
                  longitude:
                    type: number
                  planets:
                    type: object
                    additionalProperties:
                      type: string
                  planet_houses:
                    type: object
                    additionalProperties:
                      type: string
                  retrograde:
                    type: object
                    additionalProperties:
                      type: boolean
                  houses:
                    type: object
                    additionalProperties:
                      type: string
                  angles:
                    type: object
                    properties:
                      ASC:
                        type: number
                      MC:
                        type: number
        "400":
          description: 不正なリクエストまたはエラー
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /transit:
    post:
      operationId: getTransit
      summary: 現在時刻・現在地のトランジット天体情報を取得（ハウス情報なし）
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                location:
                  type: string
                  example: Tokyo, Japan
                latitude:
                  type: number
                  example: 35.6895
                longitude:
                  type: number
                  example: 139.6917
      responses:
        "200":
          description: トランジット情報取得成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  datetime_utc:
                    type: string
                    example: 2025-06-05 10:00
                  planets:
                    type: object
                    additionalProperties:
                      type: string
                  retrograde:
                    type: object
                    additionalProperties:
                      type: boolean
        "400":
          description: 不正なリクエストまたはエラー
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /solararc:
    post:
      operationId: getSolarArc
      summary: Solar Arc進行法による天体の進行位置を取得（ハウス情報なし）
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                birth_year:
                  type: integer
                  example: 1985
                birth_month:
                  type: integer
                  example: 7
                birth_day:
                  type: integer
                  example: 3
                birth_hour:
                  type: integer
                  example: 14
                birth_minute:
                  type: integer
                  example: 30
                location:
                  type: string
                  example: Tokyo, Japan
                target_year:
                  type: integer
                  example: 2025
                target_month:
                  type: integer
                  example: 6
                target_day:
                  type: integer
                  example: 5
              required:
                - birth_year
                - birth_month
                - birth_day
                - birth_hour
                - birth_minute
                - target_year
                - target_month
                - target_day
      responses:
        "200":
          description: Solar Arc進行位置取得成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  progressed_date_utc:
                    type: string
                    example: 2025-06-05 00:00
                  planets:
                    type: object
                    additionalProperties:
                      type: string
        "400":
          description: 不正なリクエストまたはエラー
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
