openapi: 3.0.0
info:
  title: AstroAPI - Planet Positions
  version: 1.0.0
  description: |
    指定した日時と場所に基づいて、天体の位置・星座・ハウス・逆行情報を返すAPIです。

servers:
  - url: https://astroapi-eixi.onrender.com

paths:
  /planet:
    post:
      summary: 天体位置を取得
      description: 指定の日時と位置情報から、各天体の星座・度数・ハウス番号・逆行情報などを取得します。
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                year:
                  type: integer
                  example: 1979
                month:
                  type: integer
                  example: 5
                day:
                  type: integer
                  example: 5
                hour:
                  type: integer
                  example: 12
                minute:
                  type: integer
                  example: 30
                location:
                  type: string
                  example: "Tokyo"
                latitude:
                  type: number
                  example: 35.6895
                longitude:
                  type: number
                  example: 139.6917
              required:
                - year
                - month
                - day
                - hour
                - minute
      responses:
        '200':
          description: 天体の位置情報を含むJSONデータを返します
          content:
            application/json:
              schema:
                type: object
                properties:
                  input_datetime_utc:
                    type: string
                    example: "1979-05-05 03:51"
                  latitude:
                    type: number
                  longitude:
                    type: number
                  planets:
                    type: object
                    additionalProperties:
                      type: string
                    example:
                      Sun: "Taurus 14.1°"
                  planet_houses:
                    type: object
                    additionalProperties:
                      type: string
                    example:
                      Sun: "House 9"
                  retrograde:
                    type: object
                    additionalProperties:
                      type: boolean
                    example:
                      Sun: false
                  houses:
                    type: object
                    additionalProperties:
                      type: string
                    example:
                      House1: "Virgo 5.1°"
                  angles:
                    type: object
                    properties:
                      ASC:
                        type: number
                      MC:
                        type: number
        '400':
          description: 入力エラーまたは位置情報が不正です
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
