openapi: "3.1.0"
info:
  title: Astro API
  version: "1.0.0"
  description: 惑星の位置、ハウス、逆行情報などを取得する占星術API

servers:
  - url: https://astroapi-eixi.onrender.com

paths:
  /planet:
    post:
      operationId: getPlanetPositions
      summary: 惑星の位置とハウス、逆行情報を取得
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                year:
                  type: integer
                  example: 1979
                month:
                  type: integer
                  example: 5
                day:
                  type: integer
                  example: 5
                hour:
                  type: integer
                  example: 12
                minute:
                  type: integer
                  example: 30
                location:
                  type: string
                  example: Tokyo, Japan
                latitude:
                  type: number
                  example: 35.6895
                longitude:
                  type: number
                  example: 139.6917
              required:
                - year
                - month
                - day
                - hour
                - minute
      responses:
        "200":
          description: 惑星データ取得成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  input_datetime_utc:
                    type: string
                    example: "1979-05-05 03:51"
                  latitude:
                    type: number
                    example: 35.7
                  longitude:
                    type: number
                    example: 139.77
                  planets:
                    type: object
                    additionalProperties:
                      type: string
                    example:
                      Sun: "Taurus 14.1°"
                      Moon: "Leo 24.7°"
                  planet_houses:
                    type: object
                    additionalProperties:
                      type: string
                    example:
                      Sun: "House 9"
                      Moon: "House 12"
                  retrograde:
                    type: object
                    additionalProperties:
                      type: boolean
                    example:
                      Saturn: true
                      Sun: false
                  houses:
                    type: object
                    additionalProperties:
                      type: string
                    example:
                      House1: "Virgo 5.1°"
                      House2: "Libra 3.4°"
                  angles:
                    type: object
                    properties:
                      ASC:
                        type: number
                        example: 155.12
                      MC:
                        type: number
                        example: 62.04
        "400":
          description: 不正なリクエストまたはエラー
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Location not found"
