openapi: 3.1.0
info:
  title: Astro API
  description: 占星術API。出生図・トランジット・ソーラーアークの天体データを取得できます。
  version: "1.0.0"

servers:
  - url: https://astroapi-eixi.onrender.com

paths:
  /planet:
    post:
      summary: 出生図の計算
      operationId: getNatalChart
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PlanetRequest'
      responses:
        '200':
          description: 成功レスポンス
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlanetResponse'

  /transit:
    post:
      summary: トランジットの計算
      operationId: getTransit
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransitRequest'
      responses:
        '200':
          description: 成功レスポンス
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransitResponse'

  /solararc:
    post:
      summary: ソーラーアークの計算
      operationId: getSolarArc
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SolarArcRequest'
      responses:
        '200':
          description: 成功レスポンス
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SolarArcResponse'

components:
  schemas:
    PlanetRequest:
      type: object
      properties:
        year:
          type: integer
        month:
          type: integer
        day:
          type: integer
        hour:
          type: integer
        minute:
          type: integer
        location:
          type: string
        latitude:
          type: number
        longitude:
          type: number
      required: [year, month, day, hour, minute]

    PlanetResponse:
      type: object
      properties:
        input_datetime_utc:
          type: string
        latitude:
          type: number
        longitude:
          type: number
        planets:
          type: object
          additionalProperties:
            type: string
        planet_houses:
          type: object
          additionalProperties:
            type: string
        retrograde:
          type: object
          additionalProperties:
            type: boolean
        houses:
          type: object
          additionalProperties:
            type: string
        angles:
          type: object
          additionalProperties:
            type: number

    TransitRequest:
      $ref: '#/components/schemas/PlanetRequest'

    TransitResponse:
      type: object
      properties:
        input_datetime_utc:
          type: string
        latitude:
          type: number
        longitude:
          type: number
        planets:
          type: object
          additionalProperties:
            type: string
        retrograde:
          type: object
          additionalProperties:
            type: boolean

    SolarArcRequest:
      type: object
      properties:
        natal:
          $ref: '#/components/schemas/PlanetRequest'
        target:
          $ref: '#/components/schemas/PlanetRequest'
      required: [natal, target]

    SolarArcResponse:
      type: object
      properties:
        solar_arc:
          type: number
        progressed_planets:
          type: object
          additionalProperties:
            type: string
