openapi: 3.1.0
info:
  title: Astro API
  version: 1.0.0
  description: 惑星の位置、ハウス、逆行情報などを取得する占星術API
servers:
  - url: https://astroapi-eixi.onrender.com
paths:
  /planet:
    post:
      operationId: getPlanetPositions
      summary: 惑星の位置とハウス、逆行情報を取得
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                year:
                  type: integer
                month:
                  type: integer
                day:
                  type: integer
                hour:
                  type: integer
                minute:
                  type: integer
                location:
                  type: string
                latitude:
                  type: number
                longitude:
                  type: number
              required:
                - year
                - month
                - day
                - hour
                - minute
      responses:
        "200":
          description: 惑星データ取得成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  input_datetime_utc:
                    type: string
                  latitude:
                    type: number
                  longitude:
                    type: number
                  planets:
                    type: object
                    additionalProperties:
                      type: string
                  planet_houses:
                    type: object
                    additionalProperties:
                      type: string
                  retrograde:
                    type: object
                    additionalProperties:
                      type: boolean
                  houses:
                    type: object
                    additionalProperties:
                      type: string
                  angles:
                    type: object
                    properties:
                      ASC:
                        type: number
                      MC:
                        type: number
        "400":
          description: 不正なリクエストまたはエラー
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /transit:
    post:
      operationId: getTransitPositions
      summary: 現在時刻または指定時刻における天体の位置（ハウスなし）
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                year:
                  type: integer
                month:
                  type: integer
                day:
                  type: integer
                hour:
                  type: integer
                minute:
                  type: integer
                location:
                  type: string
                latitude:
                  type: number
                longitude:
                  type: number
      responses:
        "200":
          description: トランジット天体位置取得成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  datetime_utc:
                    type: string
                  planets:
                    type: object
                    additionalProperties:
                      type: string
                  retrograde:
                    type: object
                    additionalProperties:
                      type: boolean
        "400":
          description: 不正なリクエストまたはエラー
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /solararc:
    post:
      operationId: getSolarArcPositions
      summary: Solar Arc（1年1度法）による天体の進行位置
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                birth_year:
                  type: integer
                birth_month:
                  type: integer
                birth_day:
                  type: integer
                birth_hour:
                  type: integer
                birth_minute:
                  type: integer
                current_year:
                  type: integer
                current_month:
                  type: integer
                current_day:
                  type: integer
                current_hour:
                  type: integer
                current_minute:
                  type: integer
              required:
                - birth_year
                - birth_month
                - birth_day
                - birth_hour
                - birth_minute
                - current_year
                - current_month
                - current_day
                - current_hour
                - current_minute
      responses:
        "200":
          description: Solar Arc進行天体位置取得成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  solar_arc_degree:
                    type: number
                  progressed_planets:
                    type: object
                    additionalProperties:
                      type: string
        "400":
          description: 不正なリクエストまたはエラー
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
